# Character Configuration
_version: 1
Buffs:
  InstantBuff:
  SelfBuff:
  BotBuff:
  CombatBuff:
  GroupBuff:
Abilities:
  - Ability: Kick
UseItems:
  Shrink: 
General:
  debugLevel: off
AssistSettings:
  meleeStickDistance: 15
  meleeStickPoint: Behind
  rangedDistance: 100
  AutoAssistEngagePercent: 98
  # (melee/ranged/off)
  type: melee
  enabled: true
SwapItems:
  Main: 
LifeSupport:
Burn:
  LongBurn:
  FullBurn:
  QuickBurn:
Aura:
  CastAura: false
  Aura:
