# Character Configuration
Shaman:
  CanniSpells:
    CanniSpell:
  AutoCanni: false
  AutoShrinkGroup: true
  ShrinkSpell: Shrink
Nukes:
  Main:
Heals:
  Spells:
    important:
      - spell: Spirit Salve
        threshold: 50
        priority: 430
        gem: 2
    tank:
      - spell: Spirit Salve
        threshold: 60
        priority: 450
        gem: 2
    normal:
      - spell: Spirit Salve
        threshold: 50
        priority: 400
        gem: 2
  Tanks:
  TankHeal:
  ImportantBotHeal:
  PetHeal:
  HealOverTimeSpell:
  WhoToHeal:
    Pets: Pets
    Tank: Tank
    ImportantBot: ImportantBot
    GroupMembers: GroupMembers
  PetOwners:
  ImportantBots:
  XTargets:
DotsOnCommand:
  Main:
DotsOnAssist:
  Main:
    - spell: Drowsy
      gem: 4
Debuff:
  DebuffTargetsOnXTarEnabled: true
  MinimumAmountToStartDebuffOnXTar : 2
  DebuffOnXTar:
    Main:
      - spell: Drowsy
        gem: 4
        priority: 180
      - spell: Malaisement
        gem: 3
  DebuffOnCommand:
    Main:
  DebuffOnAssist:
    Main:
      - spell: Drowsy
        gem: 4
        priority: 180
      - spell: Malaisement
        gem: 3
        priority: 150
  DebuffOnCommand:
General:
  debugLevel: off
  maxDistance: 250
  medStop: 100
  medStart: 70
LifeSupport:
SwapItems:
  Main:
UseItems:
  Shrink:
Buffs:
  BotBuff:
    - spell: Quickness
      charactersToBuff:
        - Heezel
        - Booguu
        - Weetel
      gem: 5
    - spell: Spirit of Ox
      charactersToBuff:
        - Yeesel
        - Heezel
        - Weetel
        - Deepel
      gem: 6
    - spell: Raging Strength
      charactersToBuff:
        - Yeesel
        - Heezel
        - Weetel
        - Deepel
      gem: 7
    - spell: Spirit of Bih`li
      charactersToBuff:
        - Yeesel
        - Heezel
        - Weetel
        - Deepel
      gem: 7
    - spell: Talisman of Tnarg
      charactersToBuff:
        - Yeesel
        - Heezel
        - Weetel
        - Deepel
      gem: 8
  CombatBuff:
  GroupBuff:
  InstantBuff:
  SelfBuff:
    #- spell: Feet like Cat
    #  gem: 5
    - spell: Spirit of Ox
      gem: 6
    - spell: Raging Strength
      gem: 7
    - spell: Talisman of Tnarg
      gem: 8
Aura:
  Aura:
  CastAura: false
_version: 1
AssistSettings:
  # (melee/ranged/off)
  type: 'off'
  enabled: true
  meleeStickDistance: 15
  meleeStickPoint: Behind
  rangedDistance: 100
  AutoAssistEngagePercent: 98
Burn:
  FullBurn:
  QuickBurn:
  LongBurn: