# Character Configuration
Shaman:
  CanniSpells:
    CanniSpell: 


  AutoCanni: false

Nukes:
  Main:
    - spell: Frost Rift
      gem: 3

Heals:
  Spells:
    important:
      - spell: Minor Healing
        threshold: 50
        priority: 430
        gem: 1
    tank:
      - spell: Minor Healing
        threshold: 60
        priority: 450
        gem: 1
    normal:
      - spell: Minor Healing
        threshold: 50
        priority: 400
        gem: 1
  Tanks:

  TankHeal:

  ImportantBotHeal:

  PetHeal:

  HealOverTimeSpell:

  WhoToHeal:
    Pets: Pets
    Tank: Tank
    ImportantBot: ImportantBot
    GroupMembers: GroupMembers
  PetOwners:
  ImportantBots:
  XTargets:

DotsOnCommand:
  Main:


DotsOnAssist:
  Main:


General:
  debugLevel: off
  medStop: 100
  medStart: 70


LifeSupport:

SwapItems:
  Main: 


UseItems:
  Shrink: 


Buffs:
  BotBuff:
    - spell: Feet like Cat
      charactersToBuff:
        - Yeesel
        - Heezel
        - Weetel
        - Deepel
      gem: 5
  CombatBuff:

  GroupBuff:

  InstantBuff:

  SelfBuff:
    - spell: Feet like Cat
      gem: 5
Aura:
  Aura:

  CastAura: false


_version: 1

AssistSettings:
  # (melee/ranged/off)
  type: Off

  enabled: true

  meleeStickDistance: 15

  meleeStickPoint: Behind

  rangedDistance: 100

  AutoAssistEngagePercent: 98


Burn:
  FullBurn:

  QuickBurn:

  LongBurn:


