# Character Configuration
UseItems:
  Shrink:
AssistSettings:
  enabled: true
  meleeStickDistance: 15
  meleeStickPoint: Behind
  rangedDistance: 100
  AutoAssistEngagePercent: 98
  # (melee/ranged/off)
  type: 'off'
Aura:
  Aura:
  CastAura: false
Buffs:
  GroupBuff:
  InstantBuff:
  SelfBuff:
    #- spell: Minor Shielding
    #  gem: 8
  BotBuff:
  CombatBuff:
Wizard:
  EvacSpell:
  AutoHarvest: false
  Harvest:
    spells:
      spell:
Jolts:
  JoltThreshold: 80
  LockoutThreshold: 100
  Main:
    - spell: Concussion # caster
      gem: 5
      aggroThreshold: 80
Nukes:
  Main:
    - spell: Conflagration
      gem: 1
SwapItems:
  Main:
_version: 1
General:
  debugLevel: off
  maxDistance: 250
  medStop: 100
  medStart: 70
LifeSupport:
Burn:
  QuickBurn:
  LongBurn:
  FullBurn:
