# Character Configuration
UseItems:
  Shrink: 
AssistSettings:
  enabled: true
  meleeStickDistance: 15
  meleeStickPoint: Behind
  rangedDistance: 100
  AutoAssistEngagePercent: 98
  # (melee/ranged/off)
  type: Off


Aura:
  Aura:

  CastAura: false


Buffs:
  GroupBuff:
  InstantBuff:
  SelfBuff:
  BotBuff:
  CombatBuff:
Wizard:
  EvacSpell: 
  AutoHarvest: false
  Harvest:
    spells:
      spell: 
Nukes:
  Main:
    - spell: 'Blast of Cold'
      gem: 2
SwapItems:
  Main: 


_version: 1

General:
  debugLevel: off


LifeSupport:

Burn:
  QuickBurn:

  LongBurn:

  FullBurn:


