# Character Configuration
General:
  debugLevel: off
  maxDistance: 250
SwapItems:
  Main:
AssistSettings:
  meleeStickDistance: 15
  meleeStickPoint: Behind
  rangedDistance: 100
  AutoAssistEngagePercent: 98
  enabled: true
  # (melee/ranged/off)
  type: melee
_version: 1
Buffs:
  InstantBuff:
  SelfBuff:
  BotBuff:
  CombatBuff:
  GroupBuff:
DotsOnAssist:
  Main:
ShadowKnight:
  LifeTap:
Abilities:
  - Ability: Bash
DotsOnCommand:
  Main:
LifeSupport:
Burn:
  FullBurn:
  QuickBurn:
  LongBurn:
UseItems:
  Shrink:
Aura:
  Aura:
  CastAura: false

