---
AssistSettings:
  enabled: 'false'
  meleeStickDistance: 15
  meleeStickPoint: Behind
  rangedDistance: 100
  AutoAssistEngagePercent: 98
  type: melee
General:
  debugLevel: 'off'
SwapItems:
  Main: ''
UseItems:
  Shrink: ''
Burn:
  QuickBurn: []
  LongBurn: []
  FullBurn: []
Aura:
  CastAura: false
  Aura: []
LifeSupport: []
Heals:
  Tanks:
  - Weetel
  ImportantBot:
  - Yeesel
  - Ceepa
  Spells:
    important:
    - spell: Minor Healing
      threshold: 70
      priority: 430
      gem: 1
    tank:
    - spell: Minor Healing
      threshold: 80
      priority: 450
      gem: 1
    normal:
    - spell: Minor Healing
      threshold: 50
      priority: 400
      gem: 1
_version: 1
Buffs:
  InstantBuff: []
  SelfBuff:
  - gem: 2
    spell: Courage
  BotBuff:
  - charactersToBuff:
    - Ceepa
    - Heezel
    - Weetel
    - Deepel
    spell: Courage
    gem: 2
  CombatBuff: []
  GroupBuff: []
...
