# Character Configuration
General:
  debugLevel: off
  medstop: 100
  medstart: 70

LifeSupport:

Burn:
  QuickBurn:

  LongBurn:

  FullBurn:


UseItems:
  Shrink: 


AssistSettings:
  rangedDistance: 100
  AutoAssistEngagePercent: 98
  meleeStickDistance: 15
  enabled: true
  # (melee/ranged/off)
  type: 'off'
  meleeStickPoint: Behind
Aura:
  Aura:
  CastAura: false
Cleric:
  DivineArbitrationPct: 35
  EpicPct: 35
  CelestialRegenarationPct: 0
  AutoYaulp: false
  YaulpSpell:


Heals:
  Tanks:
    - Weetel
  ImportantBot:
    - Yeesel
    - Ceepa
  Spells:
    important:
      - spell: Light Healing
        threshold: 70
        priority: 430
        gem: 1
    tank:
      - spell: Light Healing
        threshold: 80
        priority: 450
        gem: 1
    normal:
      - spell: Light Healing
        threshold: 50
        priority: 400
        gem: 1


_version: 1

Buffs:
  InstantBuff:

  SelfBuff:
    - gem: 2
      spell: Center
  BotBuff:
    - charactersToBuff:
        - Ceepa
        - Heezel
        - Weetel
        - Deepel
        - Booguu
      spell: Center
      gem: 2

  CombatBuff:

  GroupBuff:


SwapItems:
  Main: 


