-- /srl help [topic]
-- Each entry is a list of lines printed to console.

local HELP = {}

HELP['topics'] = {
    '[SRL] Available help topics:',
    '[SRL]   commands   - all /srl subcommands',
    '[SRL]   filters    - include= / exclude= syntax',
    '[SRL]   buffs      - SelfBuff / BotBuff / CombatBuff',
    '[SRL]   heals      - heal spells, tanks, thresholds',
    '[SRL]   hots       - HoT and Promised heal spells',
    '[SRL]   nukes      - nuke spells, jolts, spell sets',
    '[SRL]   debuffs    - debuff spells, groups, checkBuff',
    '[SRL]   abilities  - discs, AAs, items, aggroThreshold',
    '[SRL]   burns      - QuickBurn / LongBurn / FullBurn',
    '[SRL]   cc         - crowd control / mez',
    '[SRL]   cures      - cure spells',
    '[SRL]   taunt      - taunt abilities',
    '[SRL]   bard       - melody configuration',
    '[SRL]   cleric     - Divine Arbitration / epic logic',
    '[SRL]   general    - General / medStart / DistanceSetting',
    '[SRL]',
    '[SRL] Usage: /srl help <topic>',
}

HELP['commands'] = {
    '[SRL] ===== Commands =====',
    '[SRL] Combat:',
    '[SRL]   /srl assiston          - assist on current target (must be aggressive NPC)',
    '[SRL]   /srl backoff           - stop attacking, clear target',
    '[SRL] Movement:',
    '[SRL]   /srl follow            - all bots follow you',
    '[SRL]   /srl stop              - stop following',
    '[SRL]   /srl move              - emergency move to you',
    '[SRL]   /srl navfollow         - nav-follow you',
    '[SRL]   /srl mtt               - navigate to your target',
    '[SRL] Burns & AAs:',
    '[SRL]   /srl quickburn / longburn / fullburn / epicburn',
    '[SRL]   /srl lesson / intensity / armor / staunch',
    '[SRL]   /srl expedient / throne / infusion / fellowship',
    '[SRL] Spells:',
    '[SRL]   /srl set <name>        - switch spell set (e.g. Fire, Ice, Main)',
    '[SRL]   /srl maxmobs <n>       - override max tanked mobs at runtime',
    '[SRL] Bard:',
    '[SRL]   /srl melody <name>     - start named melody',
    '[SRL]   /srl stopmelody        - stop melody',
    '[SRL] Items / NPC:',
    '[SRL]   /srl fi <item>         - find item in bags (partial match)',
    '[SRL]   /srl fmi <item>        - find missing item',
    '[SRL]   /srl turnin <item>     - turn in item to targeted NPC',
    '[SRL]   /srl say <phrase>      - say phrase at target (use _ for spaces, %t for name)',
    '[SRL] Info:',
    '[SRL]   /srl status [n]        - report unspent AAs (optional min threshold)',
    '[SRL]   /srl count             - show bots in/out of zone (local)',
    '[SRL] Admin:',
    '[SRL]   /srl reload            - reload YAML config',
    '[SRL]   /srl restart           - restart all bots',
    '[SRL]   /srl debug             - toggle debug overlay (local)',
    '[SRL]   /srl puller            - toggle puller mode (local)',
    '[SRL]   /srl help <topic>      - show help for a topic',
}

HELP['filters'] = {
    '[SRL] ===== Include / Exclude Filters =====',
    '[SRL] Most commands accept include= and exclude= filters.',
    '[SRL] Tokens: character name, class (CLR/BRD/SHM...), armor (Silk/Leather/Chain/Plate), Group',
    '[SRL]',
    '[SRL]   /srl quickburn include=Plate      - only plate wearers',
    '[SRL]   /srl follow exclude=Loewit        - everyone except Loewit',
    '[SRL]   /srl follow include=Group         - only group members',
    '[SRL]',
    '[SRL] exclude= takes priority over include= if both are set.',
}

HELP['buffs'] = {
    '[SRL] ===== Buffs =====',
    '[SRL] Buffs:',
    '[SRL]   SelfBuff:    cast on yourself, out of combat only',
    '[SRL]   BotBuff:     cast on others, out of combat only',
    '[SRL]   CombatBuff:  cast on others during combat only',
    '[SRL]',
    '[SRL] Entry format:',
    '[SRL]   - spell: My Buff Rk. III',
    '[SRL]     gem: 2',
    '[SRL]     alwaysCheck: true       # BotBuff only: also cast during combat',
    '[SRL]     charactersToBuff:       # optional: limit to specific characters',
    '[SRL]       - TankName',
    '[SRL]',
    '[SRL] Notes:',
    '[SRL]   - alwaysCheck: true makes a BotBuff entry fire in and out of combat.',
    '[SRL]   - charactersToBuff casts one at a time and waits for it to land.',
}

HELP['heals'] = {
    '[SRL] ===== Heals =====',
    '[SRL] Heals:',
    '[SRL]   Tanks:         - TankName     # highest heal priority',
    '[SRL]   ImportantBots: - HealerName   # elevated priority',
    '[SRL]   GroupThreshold: 65            # group heal when avg HP% below this',
    '[SRL]   GroupSpell:',
    '[SRL]     spell: Word of Restoration Rk. III',
    '[SRL]     gem: 7',
    '[SRL]   Spells:',
    '[SRL]     tank:',
    '[SRL]       - spell: Big Heal Rk. III',
    '[SRL]         threshold: 70          # cast when HP% at or below this',
    '[SRL]         gem: 1',
    '[SRL]     important:',
    '[SRL]       - spell: Big Heal Rk. III',
    '[SRL]         threshold: 70',
    '[SRL]         gem: 1',
    '[SRL]     normal:',
    '[SRL]       - spell: Small Heal Rk. II',
    '[SRL]         threshold: 60',
    '[SRL]         gem: 2',
    '[SRL]',
    '[SRL] Priority order: tanks > important > normal. Lowest HP within tier wins.',
}

HELP['hots'] = {
    '[SRL] ===== HoTs & Promised Heals =====',
    '[SRL] Heals:',
    '[SRL]   HoTSpells:               # heal-over-time spells',
    '[SRL]     tank:',
    '[SRL]       - spell: Restoring Winds Rk. III',
    '[SRL]         threshold: 95      # cast when HP% at or below this',
    '[SRL]         gem: 5',
    '[SRL]     normal:',
    '[SRL]       - spell: Restoring Winds Rk. III',
    '[SRL]         threshold: 90',
    '[SRL]         gem: 5',
    '[SRL]',
    '[SRL]   PromisedSpells:          # promised heals (fire when buff expires)',
    '[SRL]     tank:',
    '[SRL]       - spell: Promised Renewal Rk. III',
    '[SRL]         threshold: 95',
    '[SRL]         gem: 6',
    '[SRL]         buffer: 3          # seconds to wait after buff drops before recasting',
    '[SRL]',
    '[SRL] Notes:',
    '[SRL]   - HoTs skip if buff already present.',
    '[SRL]   - Promised heals let the buff expire (the heal fires on expiry),',
    '[SRL]     then wait buffer seconds before recasting (default 3).',
    '[SRL]   - Both fire in and out of combat. Score 92 (below Cure 95).',
}

HELP['nukes'] = {
    '[SRL] ===== Nukes, Jolts & Spell Sets =====',
    '[SRL] Nukes:',
    '[SRL]   Main:',
    '[SRL]     - spell: My Nuke Rk. III',
    '[SRL]       gem: 5',
    '[SRL]   Fire:           # switch with: /srl set Fire',
    '[SRL]     - spell: My Fire Nuke Rk. III',
    '[SRL]       gem: 5',
    '[SRL]',
    '[SRL] Jolts:            # aggro-reduction spells',
    '[SRL]   JoltThreshold: 80       # prefer jolts above this aggro %',
    '[SRL]   LockoutThreshold: 100   # stop nuking entirely at this aggro %',
    '[SRL]   Main:',
    '[SRL]     - spell: My Jolt Rk. III',
    '[SRL]       gem: 7',
    '[SRL]       aggroThreshold: 95  # optional per-entry override',
    '[SRL]',
    '[SRL] Notes:',
    '[SRL]   - /srl set <name> switches nukes and debuffs together.',
    '[SRL]   - Jolts never change with /srl set.',
    '[SRL]   - Falls back to Main if named set has no entries.',
}

HELP['debuffs'] = {
    '[SRL] ===== Debuffs =====',
    '[SRL] Debuff:',
    '[SRL]   DebuffOnAssist:',
    '[SRL]     Main:',
    '[SRL]       - spell: Malo Rk. III',
    '[SRL]         gem: 3',
    '[SRL]       - spell: Slow Rk. III',
    '[SRL]         gem: 2',
    '[SRL]         group: slow        # only one entry per group fires per target',
    '[SRL]         checkBuff: Turgur  # skip if this buff is on the target',
    '[SRL]       - spell: Backup Slow Rk. II',
    '[SRL]         gem: 4',
    '[SRL]         group: slow',
    '[SRL]         checkBuff:         # list: skip if any are present',
    '[SRL]           - Turgur',
    '[SRL]           - Backup Slow',
    '[SRL]   DebuffTargetsOnXTarEnabled: true',
    '[SRL]   MinimumAmountToStartDebuffOnXTar: 2',
    '[SRL]   DebuffOnXTar:',
    '[SRL]     Main:',
    '[SRL]       - spell: Malo Rk. III',
    '[SRL]         gem: 3',
    '[SRL]',
    '[SRL] Groups: entries sharing a group= value compete.',
    '[SRL]   checkBuff blocks the whole group if any listed buff is present.',
    '[SRL]   First ready entry in the group fires; others are skipped.',
}

HELP['abilities'] = {
    '[SRL] ===== Abilities =====',
    '[SRL] Abilities:',
    '[SRL]   - Ability: Flying Kick',
    '[SRL]     type: ability          # ability | disc | aa | item',
    '[SRL]   - Ability: Boastful Bellow',
    '[SRL]     type: aa',
    '[SRL]     stacks: true           # track recast by timer, not buff poll',
    '[SRL]     duration: 22           # optional: override spell duration (seconds)',
    '[SRL]   - Ability: My Debuff Disc',
    '[SRL]     type: disc',
    '[SRL]     debuff: true           # skip if effect already on target',
    '[SRL]   - Ability: Feign Death',
    '[SRL]     type: ability',
    '[SRL]     aggroThreshold: 80     # only fire when aggro% is at or above this',
    '[SRL]   - Ability: My Clicky',
    '[SRL]     type: item',
    '[SRL]     reagent: Black Silk    # skip if item not in inventory',
    '[SRL]',
    '[SRL] Notes:',
    '[SRL]   - One disc fires per tick with a 3s gate between activations.',
    '[SRL]   - Regular abilities have a 1.5s gate.',
    '[SRL]   - aggroThreshold works for all ability types.',
}

HELP['burns'] = {
    '[SRL] ===== Burns =====',
    '[SRL] Burn:',
    '[SRL]   QuickBurn:',
    '[SRL]     - name: Speed Focus Discipline',
    '[SRL]       type: disc',
    '[SRL]     - name: Intensity of the Resolute',
    '[SRL]       type: aa',
    '[SRL]     - name: My Clicky',
    '[SRL]       type: item',
    '[SRL]   FullBurn:',
    '[SRL]     - name: ...',
    '[SRL]   LongBurn:',
    '[SRL]     - name: ...',
    '[SRL]',
    '[SRL] Commands: /srl quickburn / longburn / fullburn / epicburn',
    '[SRL]',
    '[SRL] Notes:',
    '[SRL]   - Abilities fire top to bottom.',
    '[SRL]   - Discs are skipped if one is already active (600ms settle gap).',
    '[SRL]   - Epic is always clicked automatically on every burn.',
    '[SRL]   - Epic.name in YAML overrides the hardcoded class epic.',
}

HELP['cc'] = {
    '[SRL] ===== Crowd Control =====',
    '[SRL] CrowdControl:',
    '[SRL]   Enabled: true',
    '[SRL]   RecastBuffer: 10         # seconds before mez expires to recast',
    '[SRL]   MaxTankedMobs: 1         # leave this many mobs for tanks',
    '[SRL]   Spells:',
    '[SRL]     - spell: My AE Mez Rk. III',
    '[SRL]       gem: 4',
    '[SRL]       ae: true             # AE mez',
    '[SRL]       aeMinTargets: 2      # min mobs before using AE mez',
    '[SRL]       maxLevel: 78         # skip if target level exceeds this',
    '[SRL]     - spell: My Single Mez Rk. II',
    '[SRL]       gem: 5',
    '[SRL]',
    '[SRL] Runtime override: /srl maxmobs <n>  (resets on restart)',
}

HELP['cures'] = {
    '[SRL] ===== Cures =====',
    '[SRL] Cures:',
    '[SRL]   Spells:',
    '[SRL]     - name: Radiant Cure',
    '[SRL]       type: Poison,Disease,Curse',
    '[SRL]       spelltype: aa        # aa | spell (default spell)',
    '[SRL]     - name: My Cure Rk. III',
    '[SRL]       gem: 6',
    '[SRL]       type: Poison,Disease',
    '[SRL]     - name: My Curse Cure Rk. II',
    '[SRL]       gem: 8',
    '[SRL]       type: Curse',
    '[SRL]',
    '[SRL] type is a comma-separated list: Poison, Disease, Curse, Corruption',
    '[SRL] Uncurable debuff types are silently ignored.',
}

HELP['taunt'] = {
    '[SRL] ===== Taunt =====',
    '[SRL] Tank classes only (WAR / SHD / PAL).',
    '[SRL]',
    '[SRL] Taunt:',
    '[SRL]   Enabled: true',
    '[SRL]   Abilities:',
    '[SRL]     - name: Taunt',
    '[SRL]       type: ability        # ability | aa | disc',
    '[SRL]     - name: Bash',
    '[SRL]       type: ability',
    '[SRL]',
    '[SRL] Fires when the assist mob\'s target-of-target is a non-tank PC.',
}

HELP['bard'] = {
    '[SRL] ===== Bard Melodies =====',
    '[SRL] Bard:',
    '[SRL]   Melodies:',
    '[SRL]     dps:',
    '[SRL]       - 1',
    '[SRL]       - 2',
    '[SRL]       - 3',
    '[SRL]     mana:',
    '[SRL]       - 5',
    '[SRL]       - 6',
    '[SRL]',
    '[SRL] Gem slot numbers in twist order.',
    '[SRL] Commands: /srl melody dps    /srl stopmelody',
}

HELP['cleric'] = {
    '[SRL] ===== Cleric =====',
    '[SRL] Cleric:',
    '[SRL]   EpicPct: 35              # any group member HP% to click epic',
    '[SRL]   EpicName: Aegis of Superior Divinity',
    '[SRL]   DivineArbitrationPct: 35 # any group member HP% to use DA',
    '[SRL]   DonorMinPct: 60          # avg non-critical HP% required before DA/epic fires',
    '[SRL]   AutoYaulp: false',
    '[SRL]   YaulpSpell:',
    '[SRL]',
    '[SRL] Notes:',
    '[SRL]   - Scans ALL group members (not just tanks) for epic/DA thresholds.',
    '[SRL]   - DonorMinPct prevents DA from killing the raid to save one person.',
    '[SRL]   - hasSufficientDonors includes self as a potential donor.',
}

HELP['general'] = {
    '[SRL] ===== General Settings =====',
    '[SRL] General:',
    '[SRL]   debugLevel: off          # off | on',
    '[SRL]   DistanceSetting: 250     # max distance sender must be within for commands',
    '[SRL]   medStart: 10             # mana% to enter med mode (casters/healers)',
    '[SRL]   medStop: 100             # mana% to exit med mode',
    '[SRL]',
    '[SRL] These live in srl/config/settings.yaml (global) or per-character YAML.',
    '[SRL] Character YAML overrides global settings.',
    '[SRL]',
    '[SRL] /srl reload   - hot-reload all YAML without restarting',
    '[SRL] /srl restart  - full restart of all bots',
}

local function show(topic)
    local lines = HELP[topic] or HELP['topics']
    for _, line in ipairs(lines) do
        print(line)
    end
end

return { show = show, topics = HELP }
